site_name: Zhe's space
site_url: https://mydomain.org/mysite
theme:
  name: material


nav:
  - Welcome!: index.md
  - About Me: cv.md
  - Research: research.md
  - Publications: pubs.md
  - Contact: contact.md
