site_name: Zhe's space
site_url: https://mydomain.org/mysite

theme:
  name: material
  features:
    - navigation.tabs
    - palette.toggle
  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

      # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
         # Set the primary and accent colors for light mode
      primary: blue grey
      accent: blue grey
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      # Set the primary and accent colors for dark mode
      primary: blue grey
      accent: blue grey
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Welcome!: index.md
  - About Me: cv.md
  - Publications: pubs.md
  - Contact: contact.md
