site_name: Zhe's space
site_url: https://mydomain.org/mysite

theme:
  name: material
  features:
    - navigation.tabs
    - palette.toggle
    palette:
    - scheme: default
      primary: indigo        # 主色调（白天模式）
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: indigo        # 主色调（夜间模式）
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

plugins:
  - search
  - sitemap:
      changefreq: daily
      priority: 0.5


nav:
  - Welcome!: index.md
  - About Me: cv.md
  - Publications: pubs.md
  - Contact: contact.md
